# Generated by Django 5.0.6 on 2024-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', '남자'), ('female', '여자')], max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
