# Generated by Django 5.0.6 on 2024-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('좋아요', '좋아요'), ('보통', '보통'), ('싫어요', '싫어요')], max_length=10)),
            ],
        ),
    ]
